import{S as v,i as c,a as p}from"./assets/vendor-c145bea9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&n(y)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const L=document.querySelector(".form"),d=document.querySelector(".gallery");document.querySelector(".gallery-box");const i=document.querySelector(".loader-top"),m=document.querySelector(".loader-bottom");document.querySelector("input");const a=document.querySelector(".load-image");document.querySelector("body");let l=1,u="dog",g=40;const f=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});L.addEventListener("submit",S);a.addEventListener("click",q);async function S(s){if(s.preventDefault(),i.style.display="block",a.style.display="none",l=1,u=s.target.elements.search.value.trim(),!u){d.innerHTML="",c.info({position:"topRight",message:"Error enter any symbols"}),i.style.display="none";return}try{const{data:{hits:r,totalHits:t}}=await h(u,l);r.length>0?(i.style.display="none",d.innerHTML=b(r),f.refresh(),c.success({position:"topRight",message:`We found ${t} photos`}),a.style.display="block"):(d.innerHTML="",c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=g&&(a.style.display="none")}catch{console.log("Error")}finally{i.style.display="none",s.target.reset()}}function h(s,r){return p.defaults.baseURL="https://pixabay.com",p.get("/api/",{params:{key:"41863465-d06b5679f9cdea6a870afb83c",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})}function b(s=[]){return s.reduce((r,t)=>r+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function q(s){m.style.display="block",a.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{l+=1;const{data:{hits:n,totalHits:e}}=await h(u,l),o=Math.ceil(e/g);if(a.style.display="block",d.insertAdjacentHTML("beforeend",b(n)),f.refresh(),l===o)return a.style.display="none",c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(n){console.log(n)}finally{m.style.display="none",window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
